name: Terraform Deploy Infrastructure

on:
  push:
    branches:
      - main

env:
  ACTIONS_STEP_DEBUG: true
  AWS_DEBUG: true
  AWS_REGION: us-east-1

jobs:

  deploy-eks-cluster:
    outputs:
        cluster_name: ${{ env.EKS_CLUSTER_NAME }}
        project_name: ${{ env.PROJECT_NAME }}
        certificate_arn: ${{ env.CERTIFICATE_ARN }}
        role_arn: ${{ env.TF_VAR_ROLE_ARN }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          bash set-var-github-env.sh ${{ github.repository }} ${{ secrets.AWS_ACCOUNT_ID }}
        working-directory: ./bash 

      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.TF_VAR_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Clear AWS Credentials Cache
        run: rm -rf ~/.aws/cli/cache

      - name: Configure Terraform backend (state.tf)
        run: bash ./../bash/backend-create.sh
        working-directory: ./terraform

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.4.0
          terraform_wrapper: false
          
      - name: Terraform Init
        run: terraform init -reconfigure
        working-directory: ./terraform

      - name: Check Destroy Flag
        id: check-destroy
        run: bash ./../bash/check-destroy.sh
        working-directory: ./terraform

      - name: Terraform Plan
        id: terraform-plan
        run: terraform plan -out=tfplan
        working-directory: ./terraform

      - name: Destroy Resources (if destroy flag is true)
        if: env.DESTROY == 'true'
        run: terraform destroy -auto-approve
        working-directory: ./terraform
        continue-on-error: true

      - name: Apply Changes 
        if: env.DESTROY == 'false'
        run: terraform apply -auto-approve
        working-directory: ./terraform

      - name: Set Terraform Outputs to GitHub Env
        if: env.DESTROY == 'false'
        run: |
          bash ./../bash/set-tf-var-github-env.sh "EKS_CLUSTER_NAME" "eks_cluster_name"
          bash ./../bash/set-tf-var-github-env.sh "PROJECT_NAME" "project_name"
          bash ./../bash/set-tf-var-github-env.sh "CERTIFICATE_ARN" "certificate_arn"
        working-directory: ./terraform
      
      ## IF FAILS
      
      - name: Refresh State to Get Applied Resources (failure)
        if: failure()  
        run: terraform apply -refresh-only -auto-approve
        working-directory: ./terraform

      - name: List Changed Resources (failure)
        if: failure() 
        id: list-resources
        run: bash ./../bash/list-changed-resources.sh
        working-directory: ./terraform

      - name: Destroy Only Changed Resources (failure)
        if: failure() 
        run: bash ./../bash/destroy-changed-resources.sh
        working-directory: ./terraform

  install-eks-resources:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set environment variables
        run: |
          bash set-var-github-env.sh ${{ github.repository }} ${{ secrets.AWS_ACCOUNT_ID }}
        working-directory: ./bash 
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ needs.set-output.outputs.role_arn }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Clear AWS Credentials Cache
        run: rm -rf ~/.aws/cli/cache
    
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: workflow-output
          path: output.txt

      - name: Update kube config
        run: aws eks update-kubeconfig --name ${{ needs.set-output.outputs.cluster_name }} --region $AWS_REGION
        
      - name: Add Helm repositories
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: | 
            helm repo add bitnami https://charts.bitnami.com/bitnami
            helm repo update

      - name: Install Kubectl
        uses: azure/setup-kubectl@v3
        with:
         version: 'latest' 

      - name: Install ArgoCD using Helm and Run Helm test
        uses: WyriHaximus/github-action-helm3@v3
        with:
          exec: bash ./bash/install-argocd.sh ${{ needs.set-output.outputs.certificate_arn }}

      - name: Install LoadBalancer Controller
        uses: WyriHaximus/github-action-helm3@v3
        with:
         exec: bash ./bash/install-lb-controller.sh ${{ needs.set-output.outputs.cluster_name }}
        
      - name: Create Ingress Resource for ArgoCD
        working-directory: ./bash 
        run: bash create-ingress-resource.sh \
             ${{ needs.set-output.outputs.certificate_arn }} \ 
             ${{ needs.set-output.outputs.project_name }}

      - name: Create Argocd Project and Application
        working-directory: ./argocd
        run: | 
            kubectl apply -f project.yaml
            kubectl apply -f application.yaml